version: "3.8"

services:
  app:
   build:
    context: .
    image: php-hello-world:latest
    ports:
      - "8081:80"
    container_name: php-hello-world-app
    volumes:
      - ./php-hello-world-app:/var/www/html
